USE [master]
GO
/****** Object:  Database [tebucks]    Script Date: 11/1/2023 11:39:28 AM ******/
CREATE DATABASE [tebucks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tebucks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tebucks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tebucks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tebucks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [tebucks] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tebucks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [tebucks] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tebucks] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tebucks] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tebucks] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tebucks] SET ARITHABORT OFF 
GO
ALTER DATABASE [tebucks] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [tebucks] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tebucks] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tebucks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tebucks] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tebucks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tebucks] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tebucks] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tebucks] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tebucks] SET  ENABLE_BROKER 
GO
ALTER DATABASE [tebucks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tebucks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tebucks] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [tebucks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [tebucks] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tebucks] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [tebucks] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [tebucks] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [tebucks] SET  MULTI_USER 
GO
ALTER DATABASE [tebucks] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [tebucks] SET DB_CHAINING OFF 
GO
ALTER DATABASE [tebucks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [tebucks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [tebucks] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [tebucks] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [tebucks] SET QUERY_STORE = OFF
GO
USE [tebucks]
GO
/****** Object:  Table [dbo].[Accounts]    Script Date: 11/1/2023 11:39:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[AccountId] [int] IDENTITY(1,1) NOT NULL,
	[PersonId] [int] NOT NULL,
	[Balance] [money] NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persons]    Script Date: 11/1/2023 11:39:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LoginId] [int] NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transfers]    Script Date: 11/1/2023 11:39:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transfers](
	[TansferId] [int] IDENTITY(1,1) NOT NULL,
	[UserFromId] [int] NOT NULL,
	[UserToId] [int] NOT NULL,
	[TransferType] [varchar](50) NOT NULL,
	[TransferStatus] [varchar](50) NOT NULL,
	[Amount] [money] NOT NULL,
 CONSTRAINT [PK_Transfers] PRIMARY KEY CLUSTERED 
(
	[TansferId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 11/1/2023 11:39:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[user_id] [int] IDENTITY(1001,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password_hash] [varchar](200) NOT NULL,
	[salt] [varchar](200) NOT NULL,
 CONSTRAINT [PK_user] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_username] UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Accounts]  WITH CHECK ADD  CONSTRAINT [FK_Persons_Accounts] FOREIGN KEY([PersonId])
REFERENCES [dbo].[Persons] ([Id])
GO
ALTER TABLE [dbo].[Accounts] CHECK CONSTRAINT [FK_Persons_Accounts]
GO
ALTER TABLE [dbo].[Persons]  WITH CHECK ADD  CONSTRAINT [FK_Users_Person] FOREIGN KEY([LoginId])
REFERENCES [dbo].[users] ([user_id])
GO
ALTER TABLE [dbo].[Persons] CHECK CONSTRAINT [FK_Users_Person]
GO
ALTER TABLE [dbo].[Transfers]  WITH CHECK ADD  CONSTRAINT [FK_Transfers_From_Persons] FOREIGN KEY([UserFromId])
REFERENCES [dbo].[Persons] ([Id])
GO
ALTER TABLE [dbo].[Transfers] CHECK CONSTRAINT [FK_Transfers_From_Persons]
GO
ALTER TABLE [dbo].[Transfers]  WITH CHECK ADD  CONSTRAINT [FK_Transfers_To_Persons] FOREIGN KEY([UserToId])
REFERENCES [dbo].[Persons] ([Id])
GO
ALTER TABLE [dbo].[Transfers] CHECK CONSTRAINT [FK_Transfers_To_Persons]
GO
USE [master]
GO
ALTER DATABASE [tebucks] SET  READ_WRITE 
GO
